import { describe, it, expect } from 'vitest';
import {
  MINISIGN_PUBLIC_KEY,
  MINISIGN_PUBLIC_KEY_UNSET,
  PLUGIN_SOURCE_SIGNATURE_ASSET_SUFFIX,
  parseMinisignPublicKey,
  parseMinisignSignature,
  verifyMinisign,
  signatureFailureReason,
} from '../src/lib/plugin-signature.js';
import { makeMinisignKeypair } from './minisign-fixture.js';

// A GENUINE minisign vector generated by an INDEPENDENT implementation (pynacl:
// SigningKey(seed=0..31), key_id 11 22 33 44 55 66 77 88, prehashed BLAKE2b-512
// of the content, plus the global signature over signature||trusted_comment).
// This is the cross-implementation proof that our byte-layout parsing matches the
// real minisign wire format — a self-consistent fixture alone could pass with a
// wrong format understanding, then real `minisign -S` releases would fail. If this
// test breaks, the parser diverged from the format `release.yml`'s minisign emits.
const GOLDEN = {
  publicKeyLine: 'RWQRIjNEVWZ3iAOhB7/zzhC+HXDdGOdLwJln5NYwm6UNXx3chmQSVTG4',
  sigLine:
    'RUQRIjNEVWZ3iEVC5MzktsdlDMZ0G2KOdZUpPEapzN5JzkZHFq62Rbv5VoPQaS4ekOiu3GCGT9inPpC1p7fONuVNY8jgX13YLA8=',
  trustedComment: 'timestamp:1700000000\tfile:unreal-mcp-plugin-source-9.9.9.zip',
  globalSigLine: 'cLW9XIFt861LH7fGGxbOEvfJoCHuXYnfxPqx0BT0WuHxmxIVVJ8wyW2VvSvosuOk44kxGTg5KYysymhWG8iLBQ==',
  content: Buffer.from('unreal-mcp plugin source golden test vector v1'),
};

function goldenSignatureText(): string {
  return (
    `untrusted comment: golden vector\n` +
    `${GOLDEN.sigLine}\n` +
    `trusted comment: ${GOLDEN.trustedComment}\n` +
    `${GOLDEN.globalSigLine}\n`
  );
}

describe('minisign wire-format parsing', () => {
  it('parses a public key line into algo Ed + 8-byte key id + 32-byte key', () => {
    const pub = parseMinisignPublicKey(GOLDEN.publicKeyLine);
    expect(pub).not.toBeNull();
    expect(pub!.algorithm).toBe('Ed');
    expect(pub!.keyId.toString('hex')).toBe('1122334455667788');
    expect(pub!.publicKey.length).toBe(32);
  });

  it('parses a public key file (with the untrusted-comment line) identically', () => {
    const pub = parseMinisignPublicKey(`untrusted comment: whatever\n${GOLDEN.publicKeyLine}\n`);
    expect(pub!.keyId.toString('hex')).toBe('1122334455667788');
  });

  it('parses a 4-line signature file into algo ED + key id + 64-byte sig + trusted comment', () => {
    const sig = parseMinisignSignature(goldenSignatureText());
    expect(sig).not.toBeNull();
    expect(sig!.algorithm).toBe('ED');
    expect(sig!.keyId.toString('hex')).toBe('1122334455667788');
    expect(sig!.signature.length).toBe(64);
    expect(sig!.globalSignature.length).toBe(64);
    expect(sig!.trustedComment).toBe(GOLDEN.trustedComment);
  });

  it('returns null on malformed / truncated / empty input (fail-closed)', () => {
    expect(parseMinisignPublicKey('')).toBeNull();
    expect(parseMinisignPublicKey(null)).toBeNull();
    expect(parseMinisignPublicKey('not-base64!!!')).toBeNull();
    expect(parseMinisignPublicKey(Buffer.from('too short').toString('base64'))).toBeNull();
    expect(parseMinisignSignature('')).toBeNull();
    expect(parseMinisignSignature('untrusted comment: x\nAAAA\n')).toBeNull(); // no trusted comment line
  });
});

describe('verifyMinisign against the independent (pynacl) golden vector', () => {
  it('verifies the real cross-implementation vector', () => {
    expect(verifyMinisign(GOLDEN.publicKeyLine, goldenSignatureText(), GOLDEN.content)).toBe('verified');
  });

  it('rejects the golden vector when a single content byte is flipped', () => {
    const tampered = Buffer.from(GOLDEN.content);
    tampered[0] ^= 0x01;
    expect(verifyMinisign(GOLDEN.publicKeyLine, goldenSignatureText(), tampered)).toBe('signature-mismatch');
  });
});

describe('verifyMinisign — fail-closed gate (accept-real / reject-tampered)', () => {
  const data = Buffer.from('the plugin source zip bytes, whatever they are');

  it('verifies a freshly-signed payload (prehashed ED, the minisign default)', () => {
    const kp = makeMinisignKeypair();
    const sig = kp.sign(data);
    expect(verifyMinisign(kp.publicKeyLine, sig, data)).toBe('verified');
  });

  it('verifies a legacy (Ed, raw) signature too', () => {
    const kp = makeMinisignKeypair();
    const sig = kp.sign(data, { legacy: true });
    expect(verifyMinisign(kp.publicKeyLine, sig, data)).toBe('verified');
  });

  it('rejects a tampered payload (signature-mismatch)', () => {
    const kp = makeMinisignKeypair();
    const sig = kp.sign(data);
    const tampered = Buffer.concat([data, Buffer.from('!')]);
    expect(verifyMinisign(kp.publicKeyLine, sig, tampered)).toBe('signature-mismatch');
  });

  it('rejects an unsigned / missing signature (signature-unparsable)', () => {
    const kp = makeMinisignKeypair();
    expect(verifyMinisign(kp.publicKeyLine, null, data)).toBe('signature-unparsable');
    expect(verifyMinisign(kp.publicKeyLine, 'garbage not a signature', data)).toBe('signature-unparsable');
  });

  it('rejects a signature made with a DIFFERENT key id (key-id-mismatch)', () => {
    const signer = makeMinisignKeypair(Buffer.from('aaaaaaaaaaaaaaaa', 'hex'));
    const trusted = makeMinisignKeypair(Buffer.from('bbbbbbbbbbbbbbbb', 'hex'));
    const sig = signer.sign(data);
    expect(verifyMinisign(trusted.publicKeyLine, sig, data)).toBe('key-id-mismatch');
  });

  it('rejects a signature from a WRONG key sharing the trusted key id (signature-mismatch)', () => {
    const sharedId = Buffer.from('1234123412341234', 'hex');
    const signer = makeMinisignKeypair(sharedId); // attacker: same key id, different key material
    const trusted = makeMinisignKeypair(sharedId); // the key we actually trust
    const sig = signer.sign(data);
    expect(verifyMinisign(trusted.publicKeyLine, sig, data)).toBe('signature-mismatch');
  });

  it('rejects a tampered trusted comment (global-signature-mismatch)', () => {
    const kp = makeMinisignKeypair();
    const sig = kp.sign(data, { trustedComment: 'original comment' });
    const tampered = sig.replace('trusted comment: original comment', 'trusted comment: forged comment');
    expect(verifyMinisign(kp.publicKeyLine, tampered, data)).toBe('global-signature-mismatch');
  });

  it('fails closed when the pinned key is the un-provisioned sentinel', () => {
    const kp = makeMinisignKeypair();
    const sig = kp.sign(data);
    expect(verifyMinisign(MINISIGN_PUBLIC_KEY_UNSET, sig, data)).toBe('public-key-not-provisioned');
    expect(verifyMinisign('', sig, data)).toBe('public-key-not-provisioned');
    // The shipped default is still the sentinel (key provisioning is a follow-up).
    expect(MINISIGN_PUBLIC_KEY).toBe(MINISIGN_PUBLIC_KEY_UNSET);
    expect(verifyMinisign(MINISIGN_PUBLIC_KEY, sig, data)).toBe('public-key-not-provisioned');
  });

  it('fails closed when the pinned key itself is malformed (public-key-unparsable)', () => {
    const kp = makeMinisignKeypair();
    const sig = kp.sign(data);
    expect(verifyMinisign('this-is-not-a-key', sig, data)).toBe('public-key-unparsable');
  });
});

describe('signatureFailureReason + constants', () => {
  it('renders a distinct, actionable reason per verdict', () => {
    expect(signatureFailureReason('public-key-not-provisioned', 'x.minisig')).toMatch(/--plugin-source/);
    expect(signatureFailureReason('signature-unparsable', 'x.minisig')).toContain('x.minisig');
    expect(signatureFailureReason('signature-mismatch', 'x.minisig')).toMatch(/tampered/);
    expect(signatureFailureReason('key-id-mismatch', 'x.minisig')).toMatch(/different key/);
    expect(signatureFailureReason('global-signature-mismatch', 'x.minisig')).toMatch(/trusted comment/);
    expect(signatureFailureReason('verified', 'x.minisig')).toMatch(/verified/);
  });

  it('exposes the .minisig sibling suffix', () => {
    expect(PLUGIN_SOURCE_SIGNATURE_ASSET_SUFFIX).toBe('.minisig');
  });
});
